#!/usr/bin/env tsx
/**
 * Regenerate packages/adapters/read/salesforce/generated/field-map.ts
 * from `sf sobject describe` output. Read-only — only reads schema metadata
 * from the production org via the local sf CLI. Does NOT touch any record
 * data. Pre-condition: `make sf-login` (or `sf org login web --alias mdas-prod`).
 *
 * Run via: npm run sf:fieldmap (or make sf-fieldmap)
 *
 * The output file is checked in. PR review surfaces field renames as diffs.
 * If the diff shows a field MDAS depends on disappeared, the validator
 * (scripts/validate-salesforce-schema.ts) will fail CI and a Salesforce
 * admin needs to be consulted before merge.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const TARGET_ORG = process.env.SF_TARGET_ORG ?? 'mdas-prod';
const OBJECTS = ['Account', 'Opportunity', 'Workshop_Engagement__c'] as const;
const OUTPUT = join(
  process.cwd(),
  'packages/adapters/read/salesforce/generated/field-map.ts',
);

interface SfFieldDescribe {
  name: string;
  label: string;
  type: string;
  custom: boolean;
  nillable: boolean;
  length?: number;
  picklistValues?: { active: boolean; defaultValue: boolean; label: string; value: string }[];
  referenceTo?: string[];
}

interface SfDescribeResult {
  name: string;
  label: string;
  fields: SfFieldDescribe[];
}

interface SfCliResponse<T> {
  status: number;
  result: T;
  warnings?: unknown[];
}

function describe(sobject: string): SfDescribeResult {
  const stdout = execFileSync(
    'sf',
    ['sobject', 'describe', '--sobject', sobject, '--target-org', TARGET_ORG, '--json'],
    { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
  );
  const parsed = JSON.parse(stdout) as SfCliResponse<SfDescribeResult>;
  if (parsed.status !== 0) {
    throw new Error(`sf sobject describe ${sobject} failed: status ${parsed.status}`);
  }
  return parsed.result;
}

function header(): string {
  const stamp = new Date().toISOString();
  return `// AUTO-GENERATED by scripts/generate-sfdc-field-map.ts on ${stamp}.
// Source: \`sf sobject describe\` against the \`${TARGET_ORG}\` org.
// DO NOT EDIT BY HAND. Regenerate via: \`make sf-fieldmap\` (or \`npm run sf:fieldmap\`).
//
// This file is the source of truth for the SFDC API name → label / type /
// custom-flag map that the Salesforce adapter mapper relies on. The
// schema validator (scripts/validate-salesforce-schema.ts) cross-checks
// every field referenced in adapter SOQL constants against this map and
// fails CI on drift.

`;
}

interface GeneratedField {
  apiName: string;
  label: string;
  type: string;
  custom: boolean;
  nillable: boolean;
  length: number | null;
  referenceTo: string[];
}

function pickFields(describe: SfDescribeResult): GeneratedField[] {
  return describe.fields
    .map((f) => ({
      apiName: f.name,
      label: f.label,
      type: f.type,
      custom: f.custom,
      nillable: f.nillable,
      length: f.length ?? null,
      referenceTo: f.referenceTo ?? [],
    }))
    .sort((a, b) => a.apiName.localeCompare(b.apiName));
}

function emitTs(byObject: Record<string, GeneratedField[]>): string {
  const objectKeys = Object.keys(byObject).sort();
  const objectsTs = objectKeys
    .map((sobject) => {
      const fields = byObject[sobject]!;
      const lines = fields
        .map(
          (f) =>
            `    ${JSON.stringify(f.apiName)}: { label: ${JSON.stringify(f.label)}, type: ${JSON.stringify(
              f.type,
            )}, custom: ${f.custom}, nillable: ${f.nillable}, length: ${f.length}, referenceTo: ${JSON.stringify(
              f.referenceTo,
            )} },`,
        )
        .join('\n');
      return `  ${JSON.stringify(sobject)}: {\n${lines}\n  },`;
    })
    .join('\n');

  return `${header()}export interface SfdcFieldDescribe {
  label: string;
  type: string;
  custom: boolean;
  nillable: boolean;
  length: number | null;
  referenceTo: readonly string[];
}

export type SfdcSObjectName = ${objectKeys.map((k) => JSON.stringify(k)).join(' | ')};

export const SFDC_FIELD_MAP = {
${objectsTs}
} as const satisfies Record<SfdcSObjectName, Record<string, SfdcFieldDescribe>>;

export const SFDC_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
export const SFDC_GENERATED_FROM_ORG = ${JSON.stringify(TARGET_ORG)};
`;
}

function main(): void {
  const byObject: Record<string, GeneratedField[]> = {};
  for (const sobject of OBJECTS) {
    process.stderr.write(`[sf:fieldmap] describing ${sobject} from ${TARGET_ORG}...\n`);
    const d = describe(sobject);
    byObject[sobject] = pickFields(d);
    process.stderr.write(
      `[sf:fieldmap]   ${sobject}: ${byObject[sobject]!.length} fields\n`,
    );
  }
  const ts = emitTs(byObject);
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, ts);
  process.stderr.write(`[sf:fieldmap] wrote ${OUTPUT}\n`);
}

main();
