import type { AccountView, CanonicalOpportunity, ChangeEvent } from '@mdas/canonical';
import {
  parseClariManagerForecastExportCsv,
  selectLatestClariForecastValue,
  timeframeMatchesFiscalQuarter,
  type ClariForecastSelection,
  type ClariManagerForecastRow,
} from './clari-manager-forecast.js';
import {
  fiscalQuarterFromDate,
  fiscalQuarterLabel,
  fiscalQuarterStart,
} from './fiscal.js';

export {
  fiscalQuarterFromDate,
  fiscalQuarterLabel,
  fiscalQuarterStart,
} from './fiscal.js';
export type { FiscalQuarter } from './fiscal.js';

// PR-C3 — re-export Clari CSV + dark-account helpers from the public
// surface of @mdas/forecast-generator.
export { generateClariCsv, findDarkAccounts } from './clari-csv.js';
export type { ClariCsvOptions, DarkAccount } from './clari-csv.js';

export {
  parseClariManagerForecastExportCsv,
  parseClariNumericDataValue,
  selectLatestClariForecastValue,
  timeframeMatchesFiscalQuarter,
  CLARI_FORECAST_SOURCE_LABEL,
} from './clari-manager-forecast.js';
export type {
  ClariForecastSelection,
  ClariManagerForecastRow,
  SelectClariForecastValueOpts,
} from './clari-manager-forecast.js';

export interface ForecastInput {
  views: AccountView[];
  changeEvents: ChangeEvent[];
  /** ISO YYYY-MM-DD; the quarter containing this date is "current". */
  asOfDate: string;
  /** Free-text — included for compatibility with the old API. */
  audience?: string;
  /**
   * Optional managerial input. When provided, the generator computes
   * Gap to Plan; otherwise a `[fill in]` placeholder is emitted so
   * leadership knows the field is intentionally blank.
   */
  plan?: { currentQuarterUSD?: number; nextQuarterUSD?: number };
  /**
   * Pasted Clari manager forecast export CSV (same columns as the
   * export: Role, Timeframe, Field, Week, Data Type, Data Value, …).
   * When present, headline **Churn/Downsell Flash / Most Likely** (and
   * optional Plan / Hedge from matching Forecast Value rows) are read
   * deterministically — account roll-ups never override Flash.
   */
  clariManagerForecastCsv?: string;

  /**
   * Per-quarter qualitative narrative (3–5 sentences) generated by an
   * upstream LLM call (Glean Adaptive chat) that answers "how healthy
   * is this quarter today and how is it trending?". Rendered as a
   * `Health Snapshot:` block between the KPI lines (Hedge) and the
   * `Accounts with Hedge` section.
   *
   * Pure renderer contract: this package does NOT call an LLM. The
   * web API orchestrates the trajectory query + Glean chat and passes
   * the resulting string(s) here. When the LLM call fails the caller
   * passes `'[Narrative unavailable — Glean call failed]'` (or
   * similar) so the section still renders and the manager knows to
   * write it manually. When undefined the section is omitted entirely.
   */
  healthSnapshot?: {
    /** Narrative for the quarter containing `asOfDate`. */
    currentQuarter?: string;
    /** Narrative for the quarter after `asOfDate`. */
    nextQuarter?: string;
  };

  /**
   * Per-account soft-context blurbs generated by an upstream Glean
   * Adaptive chat call. Keyed by canonical `accountId`. When present
   * for an account that appears in a Key Saves bullet, the blurb is
   * appended to the bullet with a `Glean:` prefix so leadership can
   * see the qualitative "why is this on the list" without needing to
   * dig through Slack / Gmail / account-plan threads themselves.
   *
   * The string itself may be the stale-marker
   * `'[Glean context unavailable — <reason>]'` per 2026-05-21 user
   * feedback. We render it verbatim so the manager sees that they
   * need to write the why themselves before pasting into the call.
   * When the key is absent the bullet renders without a Glean tail
   * (same shape as today).
   *
   * Pure renderer contract: this package does NOT call Glean. The
   * web API orchestrates the lookup and passes the map here.
   */
  accountContext?: Record<string, string>;

  /**
   * Emerging-risk accounts that Glean flagged from soft signals
   * (Slack churn-talk, escalation threads, exec emails, account
   * plans) but that the structured down-forecast filter did NOT
   * pick up. Rendered as a sibling sub-section under
   * `Churn-save targets not yet hedged in Clari (ATR exposed)` so
   * leadership sees the "MDAS says hedge these" line AND the
   * "Glean says these accounts are smoldering" line side by side.
   *
   * Each entry carries the canonical accountId so the renderer can
   * de-duplicate against accounts already on the structured list
   * (Glean often surfaces the same names; we render Glean-flagged
   * entries only when they're not already structurally flagged).
   *
   * Bounded to the current quarter by the upstream call. Empty /
   * undefined means the sub-section is omitted entirely.
   */
  gleanFlaggedRisks?: GleanFlaggedRisk[];

  /**
   * Per-account action plans for the "Accounts to Close Gap" section,
   * keyed by canonical `accountId`. Each plan is a short checklist of
   * owner→action steps (internal owner — Account Owner / Assigned CSE
   * / Sales Engineer — paired with the concrete next move to close the
   * gap), generated fresh every run by an upstream Glean Adaptive chat
   * call grounded in the account's structured facts + soft signals.
   *
   * The renderer splices these inline beneath the matching account's
   * "Accounts to Close Gap" bullet. When a plan carries
   * `unavailableReason` (the Glean call failed) the renderer emits a
   * stale-marker so the manager knows to write the plan themselves
   * before the leadership call — same convention as `accountContext`.
   * When a key is absent the bullet renders without an action plan
   * (back-compat with callers that don't run the Glean step).
   *
   * Pure renderer contract: this package does NOT call Glean. The web
   * API orchestrates the lookup and passes the map here.
   */
  closeGapActionPlans?: Record<string, CloseGapActionPlan>;

  /**
   * Per-opportunity qualitative brief for renewals where the CSE's
   * `forecastMostLikelyOverride` diverges from Salesforce `bestCaseUSD`.
   * Keyed by `opportunityId`. Rendered in the "ML Override ≠ Best Case"
   * section as headline roll-up + per-account customer context.
   */
  mlOverrideMismatchContext?: Record<string, MlOverrideMismatchEnrichment>;
}

/**
 * Glean-generated qualitative brief for one ML Override ≠ Best Case
 * renewal. Headline feeds the section roll-up; customerContext is the
 * manager-facing paragraph leadership reads on the churn call.
 */
export interface MlOverrideMismatchEnrichment {
  /** One-line pain headline, e.g. "Perch is a product fit problem". */
  headline: string;
  /** Optional AE vs manager forecast posture note. */
  commentary?: string;
  /** 2–4 sentence customer context paragraph. */
  customerContext: string;
  /** Set when the Glean call failed — renderer emits a stale-marker. */
  unavailableReason?: string;
}

/**
 * One owner→action step in an "Accounts to Close Gap" action plan.
 * `owner` is the responsible internal name (typically "Name (Role)",
 * e.g. "Jane Doe (Assigned CSE)"); `action` is the concrete next move.
 */
export interface CloseGapActionStep {
  owner: string;
  action: string;
}

/**
 * Action plan for a single "Accounts to Close Gap" account. Either
 * carries an ordered list of `steps`, or — when the upstream Glean
 * call failed — an `unavailableReason` so the renderer can emit a
 * stale-marker instead of silently dropping the plan.
 */
export interface CloseGapActionPlan {
  steps: CloseGapActionStep[];
  unavailableReason?: string;
}

/**
 * One Glean-flagged emerging-risk account, surfaced from soft signals
 * (Slack / Gmail / account plans / CSE notes / meeting transcripts).
 * Produced by the web API's bounded Glean call; spliced into the
 * "Churn-save targets not yet hedged" block by the renderer.
 *
 * `quarter` identifies which quarter section this belongs to so the
 * web API can return one mixed list and the renderer can split into
 * the current vs. next quarter blocks.
 */
export interface GleanFlaggedRisk {
  accountId: string;
  accountName: string;
  /** `'current'` or `'next'` quarter relative to `asOfDate`. */
  quarter: 'current' | 'next';
  /** 1–2 sentence "why this might be a save" rationale from Glean. */
  rationale: string;
}

const fmtUSD = (n: number) =>
  n === 0 ? '$0' : `$${Math.round(n).toLocaleString('en-US')}`;

const fmtSignedUSD = (n: number) => {
  if (n === 0) return '$0';
  const abs = Math.abs(Math.round(n)).toLocaleString('en-US');
  return n > 0 ? `+$${abs}` : `-$${abs}`;
};

/**
 * Render the Gap-to-Plan line value, including a parenthetical
 * `% to Plan` reading against Plan when both Flash and Plan are
 * known.
 *
 * Conventions match the leadership churn-call vocabulary (Sam
 * Lawley's Expand 1 sections: "Flashing 137% to plan"). Plan and
 * Flash are NEGATIVE loss dollars; we normalize to magnitudes for
 * the percentage so the reading is monotonic in "how much we're
 * losing vs. how much we planned to lose":
 *
 *   pct = |Flash| / |Plan| × 100
 *
 *   - 100% exactly  → "at plan" (Flash equals Plan)
 *   - > 100%        → "N% over plan"  (losing more than budgeted, BAD)
 *   - < 100%        → "N% under plan" (losing less than budgeted, GOOD)
 *
 * (Yes, "over plan" reads positive in casual English but reads as
 * "over the loss budget" in finance vocabulary — leadership uses
 * this framing in the NoAM FY27 Renewal Script. We follow the
 * house convention rather than re-invent.)
 *
 * Examples:
 *   Plan -$2,164,000, Flash -$2,435,022  → "-$271,022 (113% over plan)"
 *   Plan -$2,164,000, Flash -$1,800,000  → "+$364,000 (83% under plan)"
 *   Plan -$2,164,000, Flash -$2,164,000  → "$0 (at plan)"
 *   Plan undefined                        → "[fill in once Plan is set]"
 *   Plan = 0 (degenerate)                 → just the dollar value; no %.
 */
function formatGapToPlan(flashUSD: number, planUSD: number | undefined): string {
  if (planUSD == null) return '[fill in once Plan is set]';
  const gap = flashUSD - planUSD;
  const dollar = fmtSignedUSD(gap);
  if (planUSD === 0) return dollar;
  if (gap === 0) return `${dollar} (at plan)`;
  const pct = (Math.abs(flashUSD) / Math.abs(planUSD)) * 100;
  // Round-number leadership shorthand. We're already past the 100%
  // threshold-of-meaning, so 1-decimal precision adds clutter
  // without changing how the line is read.
  const pctStr = pct.toFixed(0);
  // gap > 0 means Flash is closer to zero than Plan = beating plan
  // = under the loss budget. gap < 0 means Flash is further from
  // zero than Plan = losing more than budgeted = over the budget.
  const direction = gap > 0 ? 'under plan' : 'over plan';
  return `${dollar} (${pctStr}% ${direction})`;
}

interface QuarterBucket {
  label: string;
  key: string;
  /**
   * Opportunity rows whose closeDate falls in this quarter, paired with
   * their parent account for downstream lookups.
   */
  rows: { view: AccountView; opp: CanonicalOpportunity }[];
}

function bucketByQuarter(
  views: AccountView[],
  asOfDate: string,
): { current: QuarterBucket; next: QuarterBucket } {
  const todayFq = fiscalQuarterFromDate(asOfDate);
  if (!todayFq) {
    // Should not happen — asOfDate is a controlled input — but emit
    // empty buckets rather than crash.
    return {
      current: { label: 'Current Quarter', key: '', rows: [] },
      next: { label: 'Next Quarter', key: '', rows: [] },
    };
  }
  // Anchor "next quarter" by adding ~3 months to asOfDate. We use UTC
  // arithmetic to avoid DST drift around February (FY boundary).
  const d = new Date(`${asOfDate}T00:00:00Z`);
  d.setUTCMonth(d.getUTCMonth() + 3);
  const nextFq = fiscalQuarterFromDate(d.toISOString());

  const current: QuarterBucket = {
    label: fiscalQuarterLabel(todayFq.key),
    key: todayFq.key,
    rows: [],
  };
  const next: QuarterBucket = {
    label: nextFq ? fiscalQuarterLabel(nextFq.key) : 'Next Quarter',
    key: nextFq?.key ?? '',
    rows: [],
  };

  for (const v of views) {
    for (const o of v.opportunities) {
      const fq = fiscalQuarterFromDate(o.closeDate);
      if (!fq) continue;
      if (fq.key === current.key) current.rows.push({ view: v, opp: o });
      else if (fq.key === next.key) next.rows.push({ view: v, opp: o });
    }
  }
  return { current, next };
}

/** True when SFDC Type is a renewal (handles “Renewal”, “Existing Business - Renewal”, etc.). */
function isRenewalLike(opp: CanonicalOpportunity): boolean {
  return String(opp.type ?? '')
    .toLowerCase()
    .includes('renewal');
}

/**
 * Forecast categories the manager has explicitly *removed* from the
 * churn-save line. Zuora's `fml_Manager_ForecastCategory__c` picklist
 * uses values like `Committed Upside`, `Targeted Upside`, `Upside`,
 * `Pipeline`, `Best Case`, `Commit`, `Omitted`, `Closed`. We
 * excluded-list the small stable "removed" set so renewals stay
 * visible across picklist drift.
 *
 * IMPORTANT: We do NOT drop the `*Upside` family — that was the
 * 2026-05-20 second-pass bug. A renewal opp can be categorized as
 * `Committed Upside` / `Targeted Upside` / `Upside` *and still* carry
 * a negative Most Likely or negative ACV delta (i.e., the rep is
 * forecasting a net downsell while also hedging some upside dollars).
 * Finale, Zello, and Kustomer are the manager-verified examples —
 * all three sit in Upside-family categories and are exactly the saves
 * the manager is carrying in Clari. The churn-save vs upsell-only
 * decision lives in `isChurnSaveTarget`, not the category filter.
 *
 * Null `forecastCategory` is treated as EXCLUDED — if SFDC has no
 * manager category at all, the opp has not been pulled onto the
 * manager's forecast line.
 */
const DROPPED_FORECAST_CATEGORIES = new Set([
  'omit',
  'omitted',
  'closed',
  'closed lost',
  'closed won',
]);

function isCarriedForecastCategory(opp: CanonicalOpportunity): boolean {
  const cat = (opp.forecastCategory ?? '').trim().toLowerCase();
  if (cat === '') return false;
  if (DROPPED_FORECAST_CATEGORIES.has(cat)) return false;
  return true;
}

/** True when SFDC stage or manager forecast category marks the opp closed. */
function isClosedOpportunity(opp: CanonicalOpportunity): boolean {
  const cat = (opp.forecastCategory ?? '').trim().toLowerCase();
  if (
    cat === 'closed' ||
    cat === 'closed won' ||
    cat === 'closed lost'
  ) {
    return true;
  }
  const stage = String(opp.stageName ?? '').trim().toLowerCase();
  return stage.includes('closed');
}

/** Won / lost when the closed outcome is explicit; otherwise generic closed. */
function closedOpportunityOutcome(
  opp: CanonicalOpportunity,
): 'won' | 'lost' | 'other' | null {
  if (!isClosedOpportunity(opp)) return null;
  const cat = (opp.forecastCategory ?? '').trim().toLowerCase();
  const stage = String(opp.stageName ?? '').trim().toLowerCase();
  const blob = `${cat} ${stage}`;
  if (blob.includes('lost')) return 'lost';
  if (blob.includes('won')) return 'won';
  return 'other';
}

/**
 * Manager-effective Forecast Most Likely for churn/downsell math.
 * When `Forecast_Most_Likely_Override__c` is set, the CSE manager's
 * value is authoritative — we do not fall through to rep ML or ACV
 * delta for dollars or down-forecast qualification.
 */
function managerForecastMostLikelyUSD(
  opp: CanonicalOpportunity,
): number | null {
  if (opp.forecastMostLikelyOverride != null) {
    return opp.forecastMostLikelyOverride;
  }
  return opp.forecastMostLikely;
}

/** Churn/downsell dollars for one renewal opp — same basis as Flash. */
function renewalDownsellChurnUSD(opp: CanonicalOpportunity): number {
  return opportunityChurnFlashUSD(opp);
}

/**
 * Renewal downsell / churn opps in the quarter for the KPI header.
 * Matches Clari Forecast → Churn & Downsell → Total tab: every
 * renewal in the quarter with a down-forecast signal (known churn,
 * negative ML, or negative ACV delta), whether open or closed.
 *
 * Hedge / Close Gap still use the narrower `isChurnSaveTarget` lens
 * (carried manager category required on open pipeline).
 */
function isRenewalDownsellChurnOpp(
  _view: AccountView,
  opp: CanonicalOpportunity,
): boolean {
  return isRenewalLike(opp) && hasDownForecastSignal(opp);
}

interface ChurnSaveHeaderSummary {
  total: number;
  openCount: number;
  closedCount: number;
  closedWon: number;
  closedLost: number;
  closedOther: number;
  openChurnUSD: number;
  closedChurnUSD: number;
}

function quarterChurnSaveHeaderSummary(
  rows: QuarterBucket['rows'],
): ChurnSaveHeaderSummary {
  let openCount = 0;
  let closedWon = 0;
  let closedLost = 0;
  let closedOther = 0;
  let openChurnUSD = 0;
  let closedChurnUSD = 0;
  for (const r of rows) {
    if (!isRenewalDownsellChurnOpp(r.view, r.opp)) continue;
    const churnUSD = renewalDownsellChurnUSD(r.opp);
    if (!isClosedOpportunity(r.opp)) {
      openCount += 1;
      openChurnUSD += churnUSD;
      continue;
    }
    closedChurnUSD += churnUSD;
    const outcome = closedOpportunityOutcome(r.opp);
    if (outcome === 'won') closedWon += 1;
    else if (outcome === 'lost') closedLost += 1;
    else closedOther += 1;
  }
  const closedCount = closedWon + closedLost + closedOther;
  return {
    total: openCount + closedCount,
    openCount,
    closedCount,
    closedWon,
    closedLost,
    closedOther,
    openChurnUSD,
    closedChurnUSD,
  };
}

/**
 * One-line renewal downsell / churn roll-up for the quarter KPI header.
 * Count matches Clari Churn & Downsell Total; dollars use the same
 * manager-override-first churn basis as Flash (override column wins
 * when set; otherwise rep ML, then ACV delta).
 */
function formatChurnSaveHeaderSummary(s: ChurnSaveHeaderSummary): string {
  if (s.total === 0) return '0 opps';
  const oppLabel =
    s.total === 1
      ? `1 opp (${s.openCount} open, ${s.closedCount} closed)`
      : `${s.total} opps (${s.openCount} open, ${s.closedCount} closed)`;
  let closedPart = `${fmtSignedUSD(s.closedChurnUSD)} closed churn`;
  if (s.closedCount > 0) {
    const breakdown: string[] = [];
    if (s.closedWon > 0) breakdown.push(`${s.closedWon} won`);
    if (s.closedLost > 0) breakdown.push(`${s.closedLost} lost`);
    if (s.closedOther > 0) breakdown.push(`${s.closedOther} other`);
    if (breakdown.length > 0) closedPart += ` (${breakdown.join(', ')})`;
  }
  return [
    oppLabel,
    `${fmtSignedUSD(s.openChurnUSD)} open churn`,
    closedPart,
  ].join(', ');
}

/**
 * True when the renewal opp has a measurable down-forecast signal —
 * the rep is forecasting renewal dollars below ATR baseline, which is
 * the definition of a churn-save situation. We check the explicit
 * dollar fields rather than relying on account bucket because the
 * manager's Clari hedge list includes Healthy-bucketed accounts with
 * down-forecast renewals (Kustomer is the verified example —
 * Healthy/Yellow account, renewal at ML -$20K + ACV delta -$15K, on
 * the hedge line in Clari).
 */
function hasDownForecastSignal(opp: CanonicalOpportunity): boolean {
  if ((opp.knownChurnUSD ?? 0) > 0) return true;
  if (!isRenewalLike(opp)) return false;
  if (opp.forecastMostLikelyOverride != null) {
    return opp.forecastMostLikelyOverride < 0;
  }
  const ml = opp.forecastMostLikely;
  if (ml != null && ml < 0) return true;
  if (opp.acvDelta != null && opp.acvDelta < 0) return true;
  return false;
}

/**
 * Per the 2026-05-20 manager feedback (and the two follow-up
 * corrections): Hedge / Close-Gap sections surface renewal opps the
 * rep is actively forecasting *down* against ATR. A row qualifies
 * when ALL of:
 *   - the opportunity is a renewal (Type contains "Renewal");
 *   - the SFDC manager forecast category is set and not in the
 *     dropped set (Omitted / Closed*) — null category means the opp
 *     hasn't been pulled onto the manager's forecast line at all;
 *   - the opp itself carries a down-forecast signal (negative ML,
 *     negative ACV delta, or known churn USD).
 *
 * Account bucket is intentionally NOT a gate — Kustomer is the
 * verified counter-example (Healthy bucket, down-forecast renewal,
 * on the manager's Clari hedge list). Forecast hedge dollars are
 * also NOT a signal on their own — Pipedrive is the verified
 * counter-example (renewals at `Upside` with $25K hedge but ML and
 * ACV delta both $0, i.e., the rep is hedging pure upside, not a
 * save).
 */
function isChurnSaveTarget(_view: AccountView, opp: CanonicalOpportunity): boolean {
  if (!isRenewalLike(opp)) return false;
  if (!isCarriedForecastCategory(opp)) return false;
  if (!hasDownForecastSignal(opp)) return false;
  return true;
}

/**
 * Per-opportunity churn/downsell for the **MDAS-estimated Flash** roll-up
 * (negative dollars, aligned to Salesforce signals that drive Clari).
 *
 * Only **renewal** opportunities contribute via forecast / ACV delta.
 * (Expand 3 scope is already enforced upstream in `getDashboardData`.)
 *
 * Inclusion matches the churn window definition:
 *   - Known churn USD (positive in SFDC) → negative of that amount (any type).
 *   - Else renewal only: when the override column is set, that value alone
 *     drives the dollar roll-up (manager-authoritative).
 *   - Else renewal only: rep `forecastMostLikely` negative → that value.
 *   - Else renewal only: canonical acvDelta negative → that value.
 *
 * We do **not** sum `ATR − positive ML` (“retention gap”) — that inflated Flash
 * vs manager / Clari roll-ups. When a Clari manager CSV is pasted, Flash still
 * comes from `selectLatestClariForecastValue` and overrides this sum.
 */
function opportunityChurnFlashUSD(opp: CanonicalOpportunity): number {
  const known = opp.knownChurnUSD ?? 0;
  if (known > 0) return -known;

  if (!isRenewalLike(opp)) return 0;

  if (opp.forecastMostLikelyOverride != null) {
    return opp.forecastMostLikelyOverride < 0
      ? opp.forecastMostLikelyOverride
      : 0;
  }

  const ml = opp.forecastMostLikely;
  if (ml != null && ml < 0) return ml;

  const ad = opp.acvDelta;
  if (ad != null && ad < 0) return ad;

  return 0;
}

/** MDAS-estimated Flash (sum of per-opp churn components). */
function mdasAccountFlashChurnUSD(rows: QuarterBucket['rows']): number {
  return rows.reduce((s, r) => s + opportunityChurnFlashUSD(r.opp), 0);
}

const CLARI_ROLE = 'FLM Expand 3';
const CLARI_DATA_TYPE = 'Forecast Value';

function clariSelectionForQuarter(
  rows: ClariManagerForecastRow[],
  fiscalQuarterKey: string,
  field: string,
): ClariForecastSelection | null {
  return selectLatestClariForecastValue(rows, {
    role: CLARI_ROLE,
    timeframeMatches: (tf) => timeframeMatchesFiscalQuarter(tf, fiscalQuarterKey),
    field,
    dataType: CLARI_DATA_TYPE,
  });
}

/**
 * "Total Risk / Baseline" = full ATR exposed across confirmed + saveable
 * accounts in the quarter (worst case, before saves).
 */
function totalRisk(rows: QuarterBucket['rows']): number {
  return rows
    .filter(
      (r) =>
        r.view.bucket === 'Confirmed Churn' ||
        r.view.bucket === 'Saveable Risk',
    )
    .reduce((s, r) => s + (r.opp.availableToRenewUSD ?? 0), 0);
}

/**
 * "Hedge" = sum of forecastHedgeUSD on churn-save renewal opps the
 * manager is carrying on the Clari hedge line.
 *
 * Per 2026-05-20 manager feedback the prior implementation summed
 * forecastHedgeUSD across ALL opps in the quarter, which double-
 * counted expansion hedge (Amendment / New Business / Contracted
 * Ramp opps with non-zero forecastHedgeUSD) into the "Hedge" KPI
 * leadership reads as renewal-save dollars. Gate to the same
 * `isChurnSaveTarget` lens as `Accounts with Hedge` — renewal +
 * carried forecast category + down-forecast signal. Upside-only
 * renewal hedges (e.g. Pipedrive at `Upside` with ML $0) are
 * excluded so the header matches Clari Churn & Downsell hedge.
 */
function hedge(rows: QuarterBucket['rows']): number {
  return rows.reduce((s, r) => {
    if (!isChurnSaveTarget(r.view, r.opp)) return s;
    return s + (r.opp.forecastHedgeUSD ?? 0);
  }, 0);
}

/**
 * Trajectory snapshot of a quarter's churn/downsell KPIs at a single
 * point in time. Plan / Flash / Gap use the same math the renderer
 * uses for the leadership-facing KPI block: identical numbers, just
 * exposed as a struct for off-line analysis (Health Snapshot
 * trajectory series, dashboards, etc.).
 */
export interface QuarterKpiSnapshot {
  /** Fiscal quarter key, e.g., `FY27Q2`. Empty when no opps land in any quarter. */
  fiscalQuarterKey: string;
  /** Display label, e.g., `FY27 Q2`. */
  fiscalQuarterLabel: string;
  /** Churn/Downsell Plan (negative USD) when supplied by caller. */
  planUSD: number | null;
  /** Churn/Downsell Flash / Most Likely (negative USD). */
  flashUSD: number;
  /** Gap to Plan (Flash - Plan). Null when Plan is unknown. */
  gapUSD: number | null;
  /** Total Churn/Downsell Risk / Baseline (negative USD). */
  totalRiskUSD: number;
  /** Hedge (positive USD). */
  hedgeUSD: number;
  /** Count of accounts in the quarter whose color-band is red. */
  redAccountCount: number;
  /** Count of accounts in the quarter whose color-band is yellow. */
  yellowAccountCount: number;
  /** Count of distinct accounts represented (across all opps in this quarter). */
  accountCount: number;
  /** Number of distinct opps in this quarter. */
  opportunityCount: number;
}

/**
 * Return the canonical accountIds that would appear in this quarter's
 * Key Saves bullets (red + yellow + green sub-lists), in the same
 * order the renderer would emit them. Used by the web API to scope
 * the per-account Glean enrichment call to exactly the accounts that
 * end up on the leadership churn-call drill-in.
 *
 * `quarter`: `'current'` (the quarter containing asOfDate) or
 * `'next'`. The red sub-list is current-quarter-only in the renderer,
 * matching the manager's NoAM FY27 Renewal Script template; we
 * mirror that here so the web-side call matches what's actually
 * rendered.
 *
 * Pure function — no DB / Glean / IO. Same `topAccountsToCloseGap`
 * filter as the renderer, deduped across the three bands so each
 * accountId appears at most once even when an account spans bands
 * via multiple opps.
 */
export function keySavesAccountIds(
  views: AccountView[],
  asOfDate: string,
  quarter: 'current' | 'next',
): string[] {
  const buckets = bucketByQuarter(views, asOfDate);
  const bucket = quarter === 'current' ? buckets.current : buckets.next;
  const ids: string[] = [];
  const seen = new Set<string>();
  const push = (band: 'red' | 'yellow' | 'green') => {
    for (const r of topAccountsToCloseGap(bucket.rows, band, 5)) {
      const id = r.view.account.accountId;
      if (seen.has(id)) continue;
      seen.add(id);
      ids.push(id);
    }
  };
  // Red is current-quarter-only in the renderer; skip it for next quarter.
  if (quarter === 'current') push('red');
  push('yellow');
  push('green');
  return ids;
}

/**
 * Lightweight context bundle for one Key Saves account, exported so
 * the web API can pass exactly the same fields the deterministic
 * chip line uses into the Glean prompt. Keeps the prompt grounded
 * in the data the manager already scans rather than asking Glean
 * to re-derive risk from scratch.
 */
export interface KeySaveAccountContext {
  accountId: string;
  accountName: string;
  band: 'red' | 'yellow' | 'green';
  cerebroRiskCategory: string | null;
  cseSentiment: string | null;
  closeDate: string;
  acvUSD: number | null;
  forecastMostLikelyUSD: number | null;
  scNextSteps: string | null;
}

/**
 * Companion to `keySavesAccountIds`: returns the full context bundles
 * the web API needs to build a per-account Glean prompt without
 * round-tripping back through the canonical types. Same ordering as
 * `keySavesAccountIds`.
 */
export function keySavesAccountContexts(
  views: AccountView[],
  asOfDate: string,
  quarter: 'current' | 'next',
): KeySaveAccountContext[] {
  const buckets = bucketByQuarter(views, asOfDate);
  const bucket = quarter === 'current' ? buckets.current : buckets.next;
  const out: KeySaveAccountContext[] = [];
  const seen = new Set<string>();
  const collect = (band: 'red' | 'yellow' | 'green') => {
    for (const r of topAccountsToCloseGap(bucket.rows, band, 5)) {
      const id = r.view.account.accountId;
      if (seen.has(id)) continue;
      seen.add(id);
      out.push({
        accountId: id,
        accountName: r.view.account.accountName,
        band,
        cerebroRiskCategory: r.view.account.cerebroRiskCategory ?? null,
        cseSentiment: r.view.account.cseSentiment ?? null,
        closeDate: r.opp.closeDate,
        acvUSD: r.opp.acv ?? null,
        forecastMostLikelyUSD: managerForecastMostLikelyUSD(r.opp),
        scNextSteps: r.opp.scNextSteps ?? null,
      });
    }
  };
  if (quarter === 'current') collect('red');
  collect('yellow');
  collect('green');
  return out;
}

/**
 * Select the accounts that appear in the "Accounts to Close Gap"
 * section for a quarter's rows: churn-save renewals in the red /
 * yellow bands, deduped to the largest-ATR opp per account, ranked by
 * ATR, then capped to the top 3 red + top 2 yellow (≤5 total).
 *
 * Extracted so the renderer and `closeGapAccountContexts` (which feeds
 * the upstream Glean action-plan call) select the EXACT same accounts —
 * the action plans must key on the accounts the manager actually sees
 * in the pasted script.
 */
function selectCloseGapAccounts(
  rows: QuarterBucket['rows'],
): { view: AccountView; opp: CanonicalOpportunity; usd: number; band: 'red' | 'yellow' }[] {
  const gapSeen = new Map<
    string,
    { view: AccountView; opp: CanonicalOpportunity; usd: number; band: 'red' | 'yellow' }
  >();
  for (const r of rows) {
    if (!isChurnSaveTarget(r.view, r.opp)) continue;
    const band = colorBand(r.view);
    if (band !== 'red' && band !== 'yellow') continue;
    const atr = r.opp.availableToRenewUSD ?? r.opp.acv ?? 0;
    if (atr <= 0) continue;
    const prev = gapSeen.get(r.view.account.accountId);
    if (!prev || atr > prev.usd) {
      gapSeen.set(r.view.account.accountId, { view: r.view, opp: r.opp, usd: atr, band });
    }
  }
  const allGap = Array.from(gapSeen.values());
  const gapReds = allGap.filter((r) => r.band === 'red').sort((a, b) => b.usd - a.usd).slice(0, 3);
  const gapYellows = allGap
    .filter((r) => r.band === 'yellow')
    .sort((a, b) => b.usd - a.usd)
    .slice(0, 2);
  return [...gapReds, ...gapYellows].slice(0, 5);
}

/**
 * Context bundle for one "Accounts to Close Gap" account, carrying the
 * internal owner names (Account Owner / Assigned CSE / Sales Engineer)
 * and the structured facts the upstream Glean action-plan prompt needs
 * to assign concrete owner→action steps without round-tripping back
 * through the canonical types.
 */
/**
 * True when the string looks like a Salesforce User Id (15/18-char
 * `005…`), not a human display name. Used to keep CRM ids out of the
 * leadership-facing action-plan script.
 */
export function isSalesforceUserId(s: string): boolean {
  return /^005[a-zA-Z0-9]{12,15}$/.test(s.trim());
}

/** Drop null/blank values and Salesforce User Ids masquerading as names. */
export function humanPersonName(name: string | null | undefined): string | null {
  if (!name) return null;
  const t = name.trim();
  if (!t || isSalesforceUserId(t)) return null;
  return t;
}

export interface CloseGapAccountContext {
  accountId: string;
  accountName: string;
  band: 'red' | 'yellow';
  atrUSD: number;
  closeDate: string;
  forecastMostLikelyUSD: number | null;
  cerebroRiskCategory: string | null;
  cseSentiment: string | null;
  scNextSteps: string | null;
  accountOwnerId: string | null;
  /** Salesforce Account Owner display name (never a User Id). */
  accountOwnerName: string | null;
  assignedCseId: string | null;
  assignedCseName: string | null;
  salesEngineerId: string | null;
  salesEngineerName: string | null;
}

/**
 * The account's Assigned CSE from Salesforce (`Assigned_CSE__c`) —
 * the ONLY owner we surface on Close-Gap action plans. Opp-level
 * Sales Engineer / Account Owner fields are intentionally excluded:
 * they often reference former employees or unrelated opps (e.g. Jayaram
 * on a legacy Arcserve opp still tied to the Zetta account).
 */
export function closeGapPrimaryOwner(ctx: CloseGapAccountContext): string {
  return ctx.assignedCseName ?? 'Assigned CSE';
}

/** Allowed action-plan owner — exactly one: the current Assigned CSE. */
export function closeGapAllowedOwnerNames(ctx: CloseGapAccountContext): string[] {
  return ctx.assignedCseName ? [ctx.assignedCseName] : [];
}

/**
 * Normalize a Glean-returned `owner` to the account's current Assigned
 * CSE. Glean frequently returns opp-level SEs, note authors, or former
 * employees — we ignore all of that and stamp every step with the CSE
 * Salesforce has on the account today.
 */
export function resolveCloseGapOwner(
  rawOwner: string,
  ctx: CloseGapAccountContext,
): string {
  const primary = closeGapPrimaryOwner(ctx);
  const owner = rawOwner.trim();
  if (!owner) return primary;
  if (ctx.assignedCseId && owner === ctx.assignedCseId && ctx.assignedCseName) {
    return ctx.assignedCseName;
  }
  if (isSalesforceUserId(owner)) return primary;
  if (
    ctx.assignedCseName &&
    owner.toLowerCase() === ctx.assignedCseName.toLowerCase()
  ) {
    return ctx.assignedCseName;
  }
  return primary;
}

/**
 * Returns the full context bundles for the accounts that appear in the
 * "Accounts to Close Gap" section of a quarter, so the web API can
 * build a per-account Glean action-plan prompt. Same selection /
 * ordering as the renderer (see `selectCloseGapAccounts`).
 */
export function closeGapAccountContexts(
  views: AccountView[],
  asOfDate: string,
  quarter: 'current' | 'next',
): CloseGapAccountContext[] {
  const buckets = bucketByQuarter(views, asOfDate);
  const bucket = quarter === 'current' ? buckets.current : buckets.next;
  return selectCloseGapAccounts(bucket.rows).map((r) => ({
    accountId: r.view.account.accountId,
    accountName: r.view.account.accountName,
    band: r.band,
    atrUSD: r.usd,
    closeDate: r.opp.closeDate,
    forecastMostLikelyUSD: managerForecastMostLikelyUSD(r.opp),
    cerebroRiskCategory: r.view.account.cerebroRiskCategory ?? null,
    cseSentiment: r.view.account.cseSentiment ?? null,
    scNextSteps: r.opp.scNextSteps ?? null,
    accountOwnerId: r.view.account.accountOwner?.id ?? null,
    accountOwnerName: humanPersonName(r.view.account.accountOwner?.name),
    assignedCseId: r.view.account.assignedCSE?.id ?? null,
    assignedCseName: humanPersonName(r.view.account.assignedCSE?.name),
    salesEngineerId: r.opp.salesEngineer?.id ?? null,
    salesEngineerName: humanPersonName(r.opp.salesEngineer?.name),
  }));
}

/** Minimum |ML Override − Best Case| gap (USD) to surface in the script. */
const ML_BC_MISMATCH_MIN_USD = 1_000;

/**
 * Dollar gap when CSE ML Override and Best Case diverge materially;
 * `null` when either field is missing or the gap is below threshold.
 */
export function mlOverrideBestCaseGap(opp: CanonicalOpportunity): number | null {
  const override = opp.forecastMostLikelyOverride;
  const bestCase = opp.bestCaseUSD;
  if (override == null || bestCase == null) return null;
  if (!Number.isFinite(override) || !Number.isFinite(bestCase)) return null;
  const gap = override - bestCase;
  if (Math.abs(gap) < ML_BC_MISMATCH_MIN_USD) return null;
  return gap;
}

/**
 * Renewal opps in the quarter where the manager-set ML Override
 * materially differs from Best Case USD, ranked by |gap| descending.
 */
export function selectMlOverrideMismatchOpps(
  rows: QuarterBucket['rows'],
  limit = 8,
): { view: AccountView; opp: CanonicalOpportunity; gapUSD: number }[] {
  const out: { view: AccountView; opp: CanonicalOpportunity; gapUSD: number }[] =
    [];
  for (const r of rows) {
    if (!isRenewalLike(r.opp)) continue;
    if (!isCarriedForecastCategory(r.opp)) continue;
    const gap = mlOverrideBestCaseGap(r.opp);
    if (gap == null) continue;
    out.push({ view: r.view, opp: r.opp, gapUSD: gap });
  }
  return out
    .sort((a, b) => Math.abs(b.gapUSD) - Math.abs(a.gapUSD))
    .slice(0, limit);
}

/** Context bundle for one ML Override ≠ Best Case renewal opp. */
export interface MlOverrideMismatchContext {
  opportunityId: string;
  accountId: string;
  accountName: string;
  opportunityName: string;
  closeDate: string;
  mlOverrideUSD: number;
  bestCaseUSD: number;
  gapUSD: number;
  forecastMostLikelyUSD: number | null;
  forecastCategory: string | null;
  cerebroRiskCategory: string | null;
  cseSentiment: string | null;
  accountOwnerName: string | null;
  assignedCseName: string | null;
  productLine: string | null;
}

/**
 * Returns context for Glean mismatch-explanation calls — same selection
 * as the renderer (see `selectMlOverrideMismatchOpps`).
 */
export function mlOverrideMismatchContexts(
  views: AccountView[],
  asOfDate: string,
  quarter: 'current' | 'next',
): MlOverrideMismatchContext[] {
  const buckets = bucketByQuarter(views, asOfDate);
  const bucket = quarter === 'current' ? buckets.current : buckets.next;
  return selectMlOverrideMismatchOpps(bucket.rows).map((r) => ({
    opportunityId: r.opp.opportunityId,
    accountId: r.view.account.accountId,
    accountName: r.view.account.accountName,
    opportunityName: r.opp.opportunityName,
    closeDate: r.opp.closeDate,
    mlOverrideUSD: r.opp.forecastMostLikelyOverride!,
    bestCaseUSD: r.opp.bestCaseUSD!,
    gapUSD: r.gapUSD,
    forecastMostLikelyUSD: managerForecastMostLikelyUSD(r.opp),
    forecastCategory: r.opp.forecastCategory ?? null,
    cerebroRiskCategory: r.view.account.cerebroRiskCategory ?? null,
    cseSentiment: r.view.account.cseSentiment ?? null,
    accountOwnerName: humanPersonName(r.view.account.accountOwner?.name),
    assignedCseName: humanPersonName(r.view.account.assignedCSE?.name),
    productLine: r.opp.productLine ?? null,
  }));
}

/**
 * Compute KPI snapshot for a single quarter (current OR next), given
 * the views + asOfDate + optional plan dollar value. Used by the web
 * API's trajectory loader to build a time-series of snapshots over
 * the quarter for the Health Snapshot LLM call.
 *
 * `quarter` chooses which quarter to compute against: `'current'`
 * (the quarter containing `asOfDate`) or `'next'`.
 */
export function computeQuarterKpis(
  views: AccountView[],
  asOfDate: string,
  quarter: 'current' | 'next',
  planUSD: number | null,
  clariRows?: ClariManagerForecastRow[],
): QuarterKpiSnapshot {
  const buckets = bucketByQuarter(views, asOfDate);
  const bucket = quarter === 'current' ? buckets.current : buckets.next;
  const mdasFlash = mdasAccountFlashChurnUSD(bucket.rows);
  const total = totalRisk(bucket.rows);
  const mdasHedgeUSD = hedge(bucket.rows);
  const clariFlash =
    clariRows && bucket.key
      ? clariSelectionForQuarter(clariRows, bucket.key, 'Churn/Downsell Flash')
      : null;
  const clariHedge =
    clariRows && bucket.key
      ? clariSelectionForQuarter(clariRows, bucket.key, 'Hedge')
      : null;
  const flash = clariFlash?.clariForecastValue ?? mdasFlash;
  const hedgeUSD = clariHedge?.clariForecastValue ?? mdasHedgeUSD;
  const uniqueAccounts = new Set<string>();
  let redCount = 0;
  let yellowCount = 0;
  const seenAccountBands = new Map<string, 'red' | 'yellow' | 'green'>();
  for (const r of bucket.rows) {
    uniqueAccounts.add(r.view.account.accountId);
    const band = colorBand(r.view);
    const prev = seenAccountBands.get(r.view.account.accountId);
    // Worst band wins (red > yellow > green) so a single red opp on
    // an account marks the account red for the count.
    if (
      !prev ||
      (band === 'red' && prev !== 'red') ||
      (band === 'yellow' && prev === 'green')
    ) {
      seenAccountBands.set(r.view.account.accountId, band);
    }
  }
  for (const band of seenAccountBands.values()) {
    if (band === 'red') redCount += 1;
    else if (band === 'yellow') yellowCount += 1;
  }
  return {
    fiscalQuarterKey: bucket.key,
    fiscalQuarterLabel: bucket.label,
    planUSD: planUSD ?? null,
    // Normalize -0 → 0 (Math.abs is overkill but explicit). Negative
    // zero leaks through `-total` when total is 0, and downstream
    // formatters / strict equality checks treat -0 ≠ 0.
    flashUSD: flash === 0 ? 0 : flash,
    gapUSD: planUSD != null ? flash - planUSD : null,
    totalRiskUSD: total === 0 ? 0 : -total,
    hedgeUSD,
    redAccountCount: redCount,
    yellowAccountCount: yellowCount,
    accountCount: uniqueAccounts.size,
    opportunityCount: bucket.rows.length,
  };
}

/** Map account → CSE-set color band. Centralized so red/yellow/green
 *  semantics stay identical across both quarter sections. */
function colorBand(view: AccountView): 'red' | 'yellow' | 'green' {
  // Confirmed Churn or Critical/High risk + Red sentiment → red.
  // Sentiment Yellow or Medium risk → yellow.
  // Otherwise (Green sentiment, Low risk, no signal) → green.
  if (
    view.bucket === 'Confirmed Churn' ||
    view.risk.level === 'Critical' ||
    view.risk.level === 'High' ||
    view.account.cseSentiment === 'Red'
  ) {
    return 'red';
  }
  if (view.risk.level === 'Medium' || view.account.cseSentiment === 'Yellow') {
    return 'yellow';
  }
  return 'green';
}

/**
 * Salesforce / Gainsight rich-text fields (FLM/SLM notes, sentiment
 * commentary, Cerebro risk analysis) often arrive as HTML pasted by
 * the CSE or surfaced by Gainsight's editor — `<p>`, `<b>`, anchor
 * tags wrapping internal links, embedded `&nbsp;` / `&amp;` /
 * `&#39;`, and the occasional decorative `<div class="tk0j8o1 ...">`.
 * Rendering that raw in the leadership churn-call script reads as
 * truncated tag-soup. This helper strips markup, decodes the
 * entities the CSE notes actually use, and collapses whitespace so
 * the prose is paste-ready.
 */
function cleanRichText(s: string | null | undefined): string {
  if (!s) return '';
  let t = String(s);
  // Drop anchor tags wholesale — the visible text is almost always
  // empty (the SFDC/Gainsight UI renders these as inline icons) and
  // the href is noise in a plaintext script.
  t = t.replace(/<a\b[^>]*>[\s\S]*?<\/a>/gi, '');
  // Replace block-level closers and <br> with single spaces so the
  // resulting prose flows; then strip remaining tags.
  t = t.replace(/<\/(p|div|li|h\d|ul|ol)>/gi, ' ');
  t = t.replace(/<br\s*\/?>(\s*)/gi, ' ');
  t = t.replace(/<[^>]+>/g, '');
  // Decode the small set of HTML entities CSE notes actually contain.
  // (We deliberately don't import a full entity decoder — every other
  // entity in observed snapshot data falls into this set.)
  t = t
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)));
  // Collapse runs of whitespace (including the spaces we just
  // inserted) and trim.
  t = t.replace(/\s+/g, ' ').trim();
  return t;
}

/** Cap narrative at maxLen graphemes, ellipsizing at a word boundary. */
function truncateNarrative(s: string, maxLen = 500): string {
  if (s.length <= maxLen) return s;
  const slice = s.slice(0, maxLen);
  const lastSpace = slice.lastIndexOf(' ');
  const cutAt = lastSpace > maxLen * 0.7 ? lastSpace : maxLen;
  return slice.slice(0, cutAt).trimEnd() + '…';
}

function keySaveBullet(
  accountName: string,
  usdLabel: string,
  detail: string,
): string {
  const d = detail.trim();
  return d ? `  - ${accountName} (${usdLabel}) - ${d}` : `  - ${accountName} (${usdLabel})`;
}

/**
 * One-line summary for the Week-over-week section header.
 *
 * Format: `net $X (regressions -$Y, improvements +$Z, N booked)`.
 * When nothing moved, returns `no movement this week`.
 *
 * Per 2026-05-20 manager feedback the header was a static label; the
 * exec couldn't tell at a glance whether the week was net-positive or
 * net-negative without reading every bullet. We now surface the dollar
 * roll-up (forecastMostLikely deltas only — see WowHeaderSummary) and a
 * booked count (renewals that hit Closed/Won this week), so the
 * leadership read is immediate.
 */
function formatWowHeaderSummary(h: WowHeaderSummary): string {
  if (
    h.net === 0 &&
    h.regressions === 0 &&
    h.improvements === 0 &&
    h.booked === 0
  ) {
    return 'no movement this week';
  }
  const parts: string[] = [];
  if (h.regressions !== 0) parts.push(`regressions ${fmtSignedUSD(h.regressions)}`);
  if (h.improvements !== 0) parts.push(`improvements ${fmtSignedUSD(h.improvements)}`);
  if (h.booked > 0) parts.push(`${h.booked} booked`);
  const tail = parts.length > 0 ? ` (${parts.join(', ')})` : '';
  return `net ${fmtSignedUSD(h.net)}${tail}`;
}

/**
 * Compact, exec-readable chip line for a Key Saves bullet.
 *
 * Per 2026-05-20 manager feedback the prior implementation pasted
 * 500-char rich-text dumps (often the CSE's State / Renewal Risk
 * commentary) under each bullet — leadership found this unreadable on
 * the churn call. We now lead with a structured chip line built from
 * the same fields the manager already scans in Clari, and the prose
 * "what's needed" follows it as a single short sentence (see
 * `keySaveNeed`).
 *
 * Chips emitted (any with a value):
 *   - Risk: Cerebro Risk Category (`Critical`/`High`/…) — leadership
 *     anchor for whether the account is in the red bucket.
 *   - Sentiment: CSE Sentiment (`Red`/`Yellow`/`Confirmed Churn`/…) —
 *     the CSE's own gut on the account.
 *   - Renewal: opportunity close date (ISO `YYYY-MM-DD`).
 *   - ML: manager-effective forecast (override when set, else rep ML)
 *     as signed USD. Down-forecasts are the reason the bullet exists.
 *
 * Chips are joined with `; ` and omitted when the underlying field is
 * empty so the line stays compact for sparse accounts.
 */
function keySaveChips(view: AccountView, opp: CanonicalOpportunity): string {
  const chips: string[] = [];
  const risk = view.account.cerebroRiskCategory;
  if (risk) chips.push(`Risk: ${risk}`);
  const sent = view.account.cseSentiment;
  if (sent) chips.push(`Sentiment: ${sent}`);
  if (opp.closeDate) chips.push(`Renewal: ${opp.closeDate}`);
  const ml = managerForecastMostLikelyUSD(opp);
  if (typeof ml === 'number' && Number.isFinite(ml) && ml !== 0) {
    chips.push(`ML: ${fmtSignedUSD(ml)}`);
  }
  return chips.join('; ');
}

/**
 * Single-sentence "what's needed" string for a Key Saves bullet.
 *
 * Per 2026-05-20 manager feedback we deliberately do NOT fall back to
 * CSE sentiment commentary, FLM/SLM notes, Cerebro risk analysis, or
 * the synthetic risk rationale — those sources produced multi-paragraph
 * dumps that drowned the chip line. SC Next Steps is the only source
 * authored as a forward-looking action by the rep on the deal, so it's
 * the only source that maps cleanly onto a one-sentence ask.
 *
 * Returns the first sentence of `opp.scNextSteps`, HTML-stripped,
 * capped at 200 chars at a word boundary. Empty string when SC Next
 * Steps is empty, so the caller renders the bullet with just the chip
 * line — which is itself a complete summary.
 */
function keySaveNeed(opp: CanonicalOpportunity): string {
  const next = cleanRichText(opp.scNextSteps);
  if (!next) return '';
  const sentenceMatch = next.match(/^[^.!?]+[.!?]/);
  const firstSentence = (sentenceMatch ? sentenceMatch[0] : next).trim();
  return truncateNarrative(firstSentence, 200);
}

/**
 * Composes the post-`($amount) - ` segment for a Key Saves bullet:
 * chip line, then (when present) a single sentence of "what's needed".
 * Returns `''` when neither has content so `keySaveBullet` drops the
 * trailing ` - `.
 */
function keySaveDetail(view: AccountView, opp: CanonicalOpportunity): string {
  const chips = keySaveChips(view, opp);
  const need = keySaveNeed(opp);
  if (chips && need) return `${chips} | ${need}`;
  return chips || need;
}

/**
 * Render a single bullet for the Hedge / not-yet-hedged / Close-Gap
 * lists with the same account+opportunity context the Key Saves
 * bullets carry. Per 2026-05-21 manager feedback the prior bullets
 * (`name ($amount) - <closeDate>`) hid the context the manager
 * already reads in Clari — Cerebro risk, CSE sentiment, forecast ML,
 * and the rep's next step. Renaming them all to the same chip-line
 * format gives leadership one consistent read across every
 * per-account list in the script.
 *
 * `dollarSuffix` is appended inside the parens (e.g., ` ATR` for the
 * ATR-sized lists, empty for the hedge list whose dollars are
 * forecastHedgeUSD).
 */
function renderAccountBullet(
  view: AccountView,
  opp: CanonicalOpportunity,
  usd: number,
  dollarSuffix = '',
  accountContext?: Record<string, string>,
): string {
  const usdLabel = `${fmtUSD(usd)}${dollarSuffix}`;
  const detail = keySaveDetail(view, opp);
  const gleanBlurb = accountContext?.[view.account.accountId]?.trim();
  // Append the Glean blurb as a second sentence-style chunk after a
  // ` || ` separator. The double-pipe distinguishes the Glean tail
  // from the existing `<chips> | <scNextSteps>` divider so leadership
  // can visually parse "structured facts | rep's next step ||
  // qualitative context". The label is `Context:` (not `Glean:`) so
  // the leadership read isn't anchored to the tool that produced it —
  // the manager treats this as "soft context the chip line couldn't
  // carry" regardless of source. When the blurb is empty (no upstream
  // call, or the call returned ''), we render the bullet exactly as
  // before — no trailing separator.
  const composedDetail = gleanBlurb
    ? detail
      ? `${detail} || Context: ${gleanBlurb}`
      : `Context: ${gleanBlurb}`
    : detail;
  return keySaveBullet(view.account.accountName, usdLabel, composedDetail);
}

/** Short product label for multi-opp account metadata lines. */
function oppProductLabel(opp: CanonicalOpportunity): string {
  const pl = opp.productLine?.trim();
  if (pl) return pl;
  const name = opp.opportunityName ?? '';
  for (const token of ['RevPro', 'Collections', 'Billing', 'CPQ', 'Revenue']) {
    if (name.toLowerCase().includes(token.toLowerCase())) return token;
  }
  return name.trim();
}

interface MlMismatchAccountGroup {
  view: AccountView;
  opps: { opp: CanonicalOpportunity; gapUSD: number }[];
}

function groupMlMismatchByAccount(
  rows: { view: AccountView; opp: CanonicalOpportunity; gapUSD: number }[],
): MlMismatchAccountGroup[] {
  const byAccount = new Map<string, MlMismatchAccountGroup>();
  for (const r of rows) {
    const id = r.view.account.accountId;
    let group = byAccount.get(id);
    if (!group) {
      group = { view: r.view, opps: [] };
      byAccount.set(id, group);
    }
    group.opps.push({ opp: r.opp, gapUSD: r.gapUSD });
  }
  return Array.from(byAccount.values()).sort((a, b) => {
    const maxA = Math.max(...a.opps.map((o) => Math.abs(o.gapUSD)));
    const maxB = Math.max(...b.opps.map((o) => Math.abs(o.gapUSD)));
    return maxB - maxA;
  });
}

function primaryMlMismatchOpp(
  group: MlMismatchAccountGroup,
): { opp: CanonicalOpportunity; gapUSD: number } {
  return [...group.opps].sort(
    (a, b) => Math.abs(b.gapUSD) - Math.abs(a.gapUSD),
  )[0]!;
}

function accountNameAppearsIn(text: string, accountName: string): boolean {
  const hay = text.toLowerCase();
  const name = accountName.trim().toLowerCase();
  if (!name) return false;
  if (hay.includes(name)) return true;
  const firstWord = name.split(/\s+/)[0] ?? '';
  return firstWord.length > 3 && hay.includes(firstWord);
}

function formatMlMismatchRollupHeadline(
  accountName: string,
  enr: MlOverrideMismatchEnrichment,
): string | null {
  let headline = enr.headline?.replace(/\s+/g, ' ').trim();
  if (!headline || enr.unavailableReason) return null;

  if (
    headline.startsWith('{') ||
    headline.includes('"headline"') ||
    headline.includes('"customerContext"')
  ) {
    const context = enr.customerContext?.replace(/\s+/g, ' ').trim();
    headline = context
      ? context.match(/^[^.!?]+[.!?]/)?.[0]?.trim().replace(/[.!?]+$/, '') ??
        context.slice(0, 120)
      : null;
    if (!headline) return null;
  }

  if (!accountNameAppearsIn(headline, accountName)) {
    headline = `${accountName} — ${headline}`;
  }
  return headline;
}

function renderMlMismatchAccountMeta(group: MlMismatchAccountGroup): string {
  const parts: string[] = [];
  const dates = [...new Set(group.opps.map((o) => o.opp.closeDate).filter(Boolean))].sort();
  if (dates.length > 0) parts.push(`Renewal: ${dates[0]}`);
  if (group.opps.length > 1) {
    const labels = [
      ...new Set(group.opps.map((o) => oppProductLabel(o.opp)).filter(Boolean)),
    ];
    if (labels.length > 0) parts.push(`Opportunities: ${labels.join(', ')}`);
  }
  const ae = humanPersonName(group.view.account.accountOwner?.name);
  if (ae) parts.push(`AE: ${ae}`);
  const cse = humanPersonName(group.view.account.assignedCSE?.name);
  if (cse) parts.push(`CSE: ${cse}`);
  return parts.join('  ');
}

/**
 * "ML Override ≠ Best Case" section: headline roll-up plus per-account
 * customer-context blocks (renewal / AE / CSE metadata, optional
 * commentary, customer context paragraph). Modeled on the manager's
 * churn-call account briefs — qualitative takeaways, not action plans.
 */
function renderMlOverrideMismatchSection(
  rows: { view: AccountView; opp: CanonicalOpportunity; gapUSD: number }[],
  enrichments: Record<string, MlOverrideMismatchEnrichment> | undefined,
): string[] {
  if (rows.length === 0) return [`  - None identified`];

  const groups = groupMlMismatchByAccount(rows);
  const lines: string[] = [];
  const headlines: string[] = [];

  for (const group of groups) {
    const primary = primaryMlMismatchOpp(group);
    const enr = enrichments?.[primary.opp.opportunityId];
    const accountName = group.view.account.accountName;
    if (enr?.unavailableReason) {
      headlines.push(`${accountName} — [context unavailable]`);
      continue;
    }
    if (!enr) continue;
    const rollup = formatMlMismatchRollupHeadline(accountName, enr);
    if (rollup) headlines.push(rollup);
  }

  if (headlines.length > 0) {
    lines.push('Headlines:');
    for (const h of headlines) lines.push(`  - ${h}`);
    lines.push('');
  }

  for (const group of groups) {
    const primary = primaryMlMismatchOpp(group);
    const enr = enrichments?.[primary.opp.opportunityId];
    lines.push(group.view.account.accountName);
    lines.push(renderMlMismatchAccountMeta(group));
    lines.push('');

    const commentary = enr?.commentary?.replace(/\s+/g, ' ').trim();
    if (commentary) {
      lines.push(`Commentary: ${commentary}`);
      lines.push('');
    }

    const context = enr?.customerContext?.replace(/\s+/g, ' ').trim();
    if (context) {
      lines.push(`Customer context: ${context}`);
    } else if (enr?.unavailableReason) {
      lines.push(
        `Customer context: [Glean context unavailable — ${enr.unavailableReason}]`,
      );
    }
    lines.push('');
  }

  return lines;
}

/**
 * Render the indented owner→action checklist beneath an "Accounts to
 * Close Gap" bullet. Returns the lines to splice in (empty array when
 * there is no plan, so the bullet renders exactly as before).
 *
 * Three shapes:
 *   - plan with steps   → `Action plan:` header + one `* owner - action`
 *                          line per step.
 *   - plan unavailable  → single stale-marker line so the manager sees
 *                          they need to write the plan before the call.
 *   - no plan (absent)  → nothing (back-compat).
 */
function renderCloseGapActionPlan(
  plan: CloseGapActionPlan | undefined,
): string[] {
  if (!plan) return [];
  if (plan.unavailableReason) {
    return [
      `      Action plan: [Glean action plan unavailable — ${plan.unavailableReason}]`,
    ];
  }
  if (plan.steps.length === 0) return [];
  const out = ['      Action plan:'];
  for (const s of plan.steps) {
    const owner = s.owner.trim();
    const action = s.action.trim();
    if (!action) continue;
    out.push(owner ? `        * ${owner} - ${action}` : `        * ${action}`);
  }
  // If every step had an empty action we emitted only the header —
  // drop it so we don't render a dangling "Action plan:" label.
  return out.length > 1 ? out : [];
}

/**
 * Top N saveable / red accounts in the quarter ordered by dollar
 * exposure. Returns one row per account (de-duplicated when an account
 * has multiple opps in the same quarter, taking the largest renewal).
 *
 * Per 2026-05-20 manager feedback: Key Saves was surfacing past-due
 * Amendment / New Business / Contracted Ramp opps because the only
 * filters were colorBand + acv > 0. An exec can't "save" an upsell
 * amendment, and the past close dates on those rows were the
 * tell-tale. We now restrict candidates to RENEWAL opps the manager
 * is still carrying on the forecast line — same `isRenewalLike` +
 * `isCarriedForecastCategory` filter the Hedge / Close-Gap sections
 * already use. We stop short of the full `isChurnSaveTarget` check
 * (which also requires a down-forecast signal) because the green band
 * legitimately contains healthy renewals the manager wants to
 * capture; an `acv > 0` renewal in forecast is a valid Key Save
 * candidate regardless of its current ML.
 */
function topAccountsToCloseGap(
  rows: QuarterBucket['rows'],
  band: 'red' | 'yellow' | 'green',
  limit = 5,
): { view: AccountView; opp: CanonicalOpportunity; usd: number }[] {
  const seen = new Map<
    string,
    { view: AccountView; opp: CanonicalOpportunity; usd: number }
  >();
  for (const r of rows) {
    if (colorBand(r.view) !== band) continue;
    if (!isRenewalLike(r.opp)) continue;
    if (!isCarriedForecastCategory(r.opp)) continue;
    const usd = r.opp.acv ?? 0;
    if (usd <= 0) continue;
    const prev = seen.get(r.view.account.accountId);
    if (!prev || usd > prev.usd) {
      seen.set(r.view.account.accountId, { view: r.view, opp: r.opp, usd });
    }
  }
  return Array.from(seen.values())
    .sort((a, b) => b.usd - a.usd)
    .slice(0, limit);
}

/**
 * Week-over-week changes scoped to the quarter's accounts.
 *
 * Per 2026-05-20 manager feedback: the WoW section was silently
 * dropping every opportunity-level diff (stage moves, forecast ML
 * changes, close-date slips) because the original implementation only
 * surfaced account-level risk/sentiment/churn-notice events. Leadership
 * lost visibility into the most actionable signals — DataStax going to
 * Closed Won, D&B's forecast improving by $100K, etc.
 *
 * Now surfaces forecast-relevant signals with thresholds to keep the
 * list signal-dense rather than noisy:
 *   - cerebroRiskCategory change (any)
 *   - cseSentiment change (any)
 *   - churn-notice category event (any — already gated on prev=null)
 *   - stageName change WHERE the new stage starts with "Closed" OR the
 *     numeric prefix jumps ≥ 2 (e.g. 3.0 → 5.0). Skips 4.0 → 5.0.
 *   - forecastMostLikely change WHERE |delta| ≥ $25,000.
 *   - closeDate change WHERE |delta| ≥ 7 days.
 *
 * Multiple events on the same account are aggregated into a single
 * line with "; "-joined detail per account. The account-level sign is
 * "-" if ANY of its events is a regression (leadership-first), else
 * "+". This pins the existing test expectations (one bullet per
 * account with the strongest signal) while now actually reporting
 * what changed.
 */
interface WowSummary {
  accountName: string;
  sign: '+' | '-';
  details: { sign: '+' | '-'; text: string }[];
}

/**
 * Dollar / count roll-up across the WoW signals, used to populate the
 * Week-over-week section header. Computed inside wowChanges() so the
 * same scoping (eligible accounts × renewal opps) that gates the
 * per-account bullets also gates the header math — leadership reads
 * the header dollar value as "what changed in our churn-save forecast
 * this week," and double-counting expansion movement would mislead.
 *
 * - regressions: sum of negative forecastMostLikely deltas across in-scope events.
 * - improvements: sum of positive forecastMostLikely deltas across in-scope events.
 * - net: regressions + improvements.
 * - booked: count of distinct accounts whose renewal opp transitioned
 *   to a Closed/Won stage during the window.
 *
 * Stage and close-date events are intentionally not assigned a dollar
 * value here — the underlying forecastMostLikely change (when present)
 * carries the dollars, and a stage-only move with no ML change should
 * not synthesize a fake number.
 */
interface WowHeaderSummary {
  net: number;
  regressions: number;
  improvements: number;
  booked: number;
}

const RISK_RANK: Record<string, number> = {
  Low: 1,
  Medium: 2,
  High: 3,
  Critical: 4,
};
const SENT_RANK: Record<string, number> = {
  Green: 3,
  Yellow: 2,
  Red: 1,
  'Confirmed Churn': 0,
};

const ML_DELTA_THRESHOLD_USD = 25_000;
const CLOSE_DATE_DELTA_THRESHOLD_DAYS = 7;

function stageNumericPrefix(stage: string): number | null {
  const m = stage.trim().match(/^(\d+(?:\.\d+)?)/);
  if (!m) return null;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : null;
}

function asNumber(v: unknown): number | null {
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  if (typeof v === 'string' && v.trim() !== '') {
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function asDateMs(v: unknown): number | null {
  if (typeof v !== 'string' || v.trim() === '') return null;
  const t = Date.parse(v);
  return Number.isFinite(t) ? t : null;
}

interface SignalDetail {
  sign: '+' | '-';
  text: string;
}

/**
 * Translate a single ChangeEvent into a leadership-relevant signal or
 * null if the event should be suppressed (sub-threshold, hygiene-only,
 * etc.). Pure function — keeps wowChanges() purely orchestrating.
 */
function eventToSignal(e: ChangeEvent): SignalDetail | null {
  if (e.field === 'cerebroRiskCategory') {
    const oldR = RISK_RANK[String(e.oldValue)] ?? 0;
    const newR = RISK_RANK[String(e.newValue)] ?? 0;
    if (newR === oldR) return null;
    return {
      sign: newR < oldR ? '+' : '-',
      text: `Risk ${e.oldValue ?? '∅'} → ${e.newValue ?? '∅'}`,
    };
  }
  if (e.field === 'cseSentiment') {
    const oldS = SENT_RANK[String(e.oldValue)] ?? 0;
    const newS = SENT_RANK[String(e.newValue)] ?? 0;
    if (newS === oldS) return null;
    return {
      sign: newS > oldS ? '+' : '-',
      text: `Sentiment ${e.oldValue ?? '∅'} → ${e.newValue ?? '∅'}`,
    };
  }
  if (e.category === 'churn-notice') {
    return { sign: '-', text: 'Churn notice submitted' };
  }
  if (e.field === 'stageName') {
    const oldStage = String(e.oldValue ?? '');
    const newStage = String(e.newValue ?? '');
    const newStartsClosed = /^\s*\d*\.?\d*\s*-?\s*Closed/i.test(newStage) ||
      newStage.toLowerCase().includes('closed');
    const oldPref = stageNumericPrefix(oldStage);
    const newPref = stageNumericPrefix(newStage);
    const jumpedFar =
      oldPref != null && newPref != null && Math.abs(newPref - oldPref) >= 2;
    if (!newStartsClosed && !jumpedFar) return null;
    // Sign: Closed Won / Closed/Won → +; Closed Lost / Closed/Lost → -;
    // mid-funnel forward jump (3.0 → 5.0) → +; backward jump → -.
    const nl = newStage.toLowerCase();
    let sign: '+' | '-' = '+';
    if (nl.includes('closed') && nl.includes('lost')) sign = '-';
    else if (nl.includes('closed') && nl.includes('won')) sign = '+';
    else if (oldPref != null && newPref != null) sign = newPref > oldPref ? '+' : '-';
    return { sign, text: `Stage ${oldStage} → ${newStage}` };
  }
  if (e.field === 'forecastMostLikely') {
    const o = asNumber(e.oldValue) ?? 0;
    const n = asNumber(e.newValue) ?? 0;
    const delta = n - o;
    if (Math.abs(delta) < ML_DELTA_THRESHOLD_USD) return null;
    return {
      sign: delta >= 0 ? '+' : '-',
      text: `Forecast ML ${fmtSignedUSD(o)} → ${fmtSignedUSD(n)} (${fmtSignedUSD(delta)})`,
    };
  }
  if (e.field === 'closeDate') {
    const o = asDateMs(e.oldValue);
    const n = asDateMs(e.newValue);
    if (o == null || n == null) return null;
    const deltaDays = Math.round((n - o) / (1000 * 60 * 60 * 24));
    if (Math.abs(deltaDays) < CLOSE_DATE_DELTA_THRESHOLD_DAYS) return null;
    return {
      sign: deltaDays <= 0 ? '+' : '-',
      text: `Close ${e.oldValue} → ${e.newValue} (${deltaDays > 0 ? '+' : ''}${deltaDays}d)`,
    };
  }
  return null;
}

function wowChanges(
  rows: QuarterBucket['rows'],
  events: ChangeEvent[],
): { summaries: WowSummary[]; header: WowHeaderSummary } {
  // Same lens as Hedge / Close-Gap (2026-05-20 manager feedback): only
  // report week-over-week movement on accounts that are themselves
  // churn-save targets — renewal opps with a forecasted downsell or
  // churn signal in the current snapshot. Expansion-only movement
  // (new business, amendments without renewal exposure, healthy
  // renewals trending up) is noise for the leadership churn call.
  const eligibleAccountIds = new Set<string>();
  // Track which opportunityIds on each eligible account are themselves
  // renewals; opp-level events on non-renewal opps for an eligible
  // account are dropped (e.g., an expansion Amendment's stage move on
  // an account that also has a down-forecast renewal).
  const renewalOppIds = new Set<string>();
  const nameById = new Map<string, string>();
  // All renewal opp IDs in the quarter (across every account), used
  // for the "recently closed-won" exception below. We need this so we
  // can promote an account into the WoW list when its renewal just
  // booked (i.e., transitioned to a Closed/Won stage during the
  // window), even though the current snapshot now categorizes the
  // renewal as Closed and isChurnSaveTarget would otherwise exclude
  // it. Leadership wants to hear about wins that just closed.
  const renewalOppToAccount = new Map<string, { accountId: string; name: string }>();

  for (const r of rows) {
    if (isRenewalLike(r.opp)) {
      renewalOppToAccount.set(r.opp.opportunityId, {
        accountId: r.view.account.accountId,
        name: r.view.account.accountName,
      });
    }
    if (!isChurnSaveTarget(r.view, r.opp)) continue;
    eligibleAccountIds.add(r.view.account.accountId);
    nameById.set(r.view.account.accountId, r.view.account.accountName);
  }

  // "Recently closed-won" exception: scan stageName events for renewal
  // opps in the quarter whose new value indicates a Closed/Won stage,
  // and promote their accounts into the eligible set. We deliberately
  // do not extend this to Closed/Lost — those rep concessions are
  // already captured by the underlying churn-save filter on prior
  // weeks (the ATR exposure was visible before it was conceded).
  for (const e of events) {
    if (e.field !== 'stageName') continue;
    if (e.opportunityId == null) continue;
    const meta = renewalOppToAccount.get(e.opportunityId);
    if (!meta) continue;
    const newStage = String(e.newValue ?? '').toLowerCase();
    if (!(newStage.includes('closed') && newStage.includes('won'))) continue;
    eligibleAccountIds.add(meta.accountId);
    nameById.set(meta.accountId, meta.name);
    renewalOppIds.add(e.opportunityId);
  }

  // Second pass: for every opportunity (in the quarter) on an
  // eligible account, mark the renewal opps so we can scope opp-level
  // diffs. We can't rely on isChurnSaveTarget here because a renewal
  // on the account may not itself trigger the filter (e.g., a second
  // renewal opp at $0 ML on the same account), but its diffs are still
  // relevant context for the manager.
  for (const r of rows) {
    if (!eligibleAccountIds.has(r.view.account.accountId)) continue;
    if (isRenewalLike(r.opp)) renewalOppIds.add(r.opp.opportunityId);
  }

  const byAccount = new Map<string, SignalDetail[]>();
  let regressions = 0;
  let improvements = 0;
  const bookedAccountIds = new Set<string>();

  for (const e of events) {
    if (!eligibleAccountIds.has(e.accountId)) continue;
    // Opp-level events only count when the opp is a renewal on this
    // account. Account-level events (no opportunityId) pass through —
    // they're sentiment / risk / churn-notice signals that already
    // describe the whole account.
    if (e.opportunityId != null && !renewalOppIds.has(e.opportunityId)) continue;
    const sig = eventToSignal(e);
    if (!sig) continue;

    // Roll up header totals from the same events we render. ML deltas
    // contribute dollars; stage→Closed/Won transitions on renewal opps
    // contribute to the `booked` count.
    if (e.field === 'forecastMostLikely') {
      const o = asNumber(e.oldValue) ?? 0;
      const n = asNumber(e.newValue) ?? 0;
      const delta = n - o;
      if (Math.abs(delta) >= ML_DELTA_THRESHOLD_USD) {
        if (delta < 0) regressions += delta;
        else improvements += delta;
      }
    } else if (
      e.field === 'stageName' &&
      e.opportunityId != null &&
      renewalOppIds.has(e.opportunityId)
    ) {
      const newStage = String(e.newValue ?? '').toLowerCase();
      if (newStage.includes('closed') && newStage.includes('won')) {
        bookedAccountIds.add(e.accountId);
      }
    }

    const list = byAccount.get(e.accountId) ?? [];
    list.push(sig);
    byAccount.set(e.accountId, list);
  }

  const summaries: WowSummary[] = [];
  for (const [accountId, details] of byAccount.entries()) {
    if (details.length === 0) continue;
    const name = nameById.get(accountId) ?? accountId;
    // Account-level sign: regression wins (leadership-first).
    const sign: '+' | '-' = details.some((d) => d.sign === '-') ? '-' : '+';
    // Stable detail order: regressions first, then improvements.
    const orderedDetails = [...details].sort((a, b) => {
      if (a.sign !== b.sign) return a.sign === '-' ? -1 : 1;
      return 0;
    });
    summaries.push({ accountName: name, sign, details: orderedDetails });
  }

  // Stable order: regressions first (leadership wants the bad news),
  // then improvements; alphabetical within each.
  const sorted = summaries.sort((a, b) => {
    if (a.sign !== b.sign) return a.sign === '-' ? -1 : 1;
    return a.accountName.localeCompare(b.accountName);
  });

  return {
    summaries: sorted,
    header: {
      net: regressions + improvements,
      regressions,
      improvements,
      booked: bookedAccountIds.size,
    },
  };
}

/**
 * Render one of the two quarter sections. Plain text — no markdown
 * links, bold, or footnotes — because the artifact is pasted into
 * Slack / email as the body of a churn forecast call.
 */
function renderQuarterSection(
  bucket: QuarterBucket,
  events: ChangeEvent[],
  planUSD: number | undefined,
  isCurrent: boolean,
  clariRows: ClariManagerForecastRow[],
  healthSnapshot: string | undefined,
  accountContext: Record<string, string> | undefined,
  gleanFlaggedRisks: GleanFlaggedRisk[] | undefined,
  closeGapActionPlans: Record<string, CloseGapActionPlan> | undefined,
  mlOverrideMismatchContext:
    | Record<string, MlOverrideMismatchEnrichment>
    | undefined,
): string[] {
  const lines: string[] = [];
  const clariFlash = clariSelectionForQuarter(
    clariRows,
    bucket.key,
    'Churn/Downsell Flash',
  );
  const clariPlan = clariSelectionForQuarter(
    clariRows,
    bucket.key,
    'Churn/Downsell Plan',
  );
  const clariHedge = clariSelectionForQuarter(clariRows, bucket.key, 'Hedge');

  const resolvedPlan = planUSD ?? clariPlan?.clariForecastValue;
  const flash =
    clariFlash?.clariForecastValue ?? mdasAccountFlashChurnUSD(bucket.rows);

  const total = totalRisk(bucket.rows);
  const hedgeUSD =
    clariHedge?.clariForecastValue ?? hedge(bucket.rows);

  lines.push(`${isCurrent ? 'Current Quarter' : 'Next Quarter'}: ${bucket.label}`);
  lines.push(
    `Churn/Downsell Plan: ${resolvedPlan != null ? fmtSignedUSD(resolvedPlan) : '[fill in]'}`,
  );
  lines.push(
    `Churn/Downsell Flash / Most Likely: ${fmtSignedUSD(flash)}`,
  );
  lines.push(`Gap to Plan: ${formatGapToPlan(flash, resolvedPlan)}`);
  lines.push(`Total Churn/Downsell Risk / Baseline: ${fmtSignedUSD(-total)}`);
  lines.push(`Hedge: ${fmtUSD(hedgeUSD)}`);
  lines.push(
    `Renewal Downsell / Churn Opps: ${formatChurnSaveHeaderSummary(
      quarterChurnSaveHeaderSummary(bucket.rows),
    )}`,
  );

  // Health Snapshot — qualitative, subjective take on the quarter's
  // health and trajectory. Sits between the dollar-KPI block and the
  // per-account sections so leadership reads the punchline before
  // the named-account drill-ins. Pure renderer: the narrative string
  // is generated upstream (Glean Adaptive chat) and passed in via
  // ForecastInput.healthSnapshot; when undefined the block is omitted
  // entirely so the deterministic test suite stays stable.
  if (healthSnapshot && healthSnapshot.trim() !== '') {
    lines.push('');
    lines.push(`Health Snapshot:`);
    lines.push(`  ${healthSnapshot.trim()}`);
    lines.push('');
  }

  // "Accounts with Hedge" — only renewal opps the manager is carrying
  // in Clari (Commit / Best Case / Pipeline) on accounts where a save
  // is still in play. Expansion-hedge opps (e.g., Pipedrive/BambooHR
  // upsells) are intentionally excluded — leadership reads this list
  // as "renewal saves we've already hedged in the forecast."
  const hedgeSeen = new Map<
    string,
    { view: AccountView; opp: CanonicalOpportunity; usd: number }
  >();
  for (const r of bucket.rows) {
    if (!isChurnSaveTarget(r.view, r.opp)) continue;
    const oppHedgeUSD = r.opp.forecastHedgeUSD ?? 0;
    if (oppHedgeUSD <= 0) continue;
    const prev = hedgeSeen.get(r.view.account.accountId);
    if (!prev || oppHedgeUSD > prev.usd) {
      hedgeSeen.set(r.view.account.accountId, {
        view: r.view,
        opp: r.opp,
        usd: oppHedgeUSD,
      });
    }
  }
  const sortedHedgeAccounts = Array.from(hedgeSeen.values())
    .sort((a, b) => b.usd - a.usd)
    .slice(0, 5);
  const churnSaveHedgeTotal = sortedHedgeAccounts.reduce(
    (s, r) => s + r.usd,
    0,
  );
  lines.push(`Accounts with Hedge (churn-save renewals): ${fmtUSD(churnSaveHedgeTotal)}`);
  if (sortedHedgeAccounts.length === 0) {
    lines.push(`  - None identified`);
  } else {
    for (const r of sortedHedgeAccounts) {
      lines.push(renderAccountBullet(r.view, r.opp, r.usd));
    }
  }
  lines.push('');

  // Renewals where the CSE's ML Override materially diverges from the
  // opp's Best Case USD — a hygiene / alignment signal leadership uses
  // to spot saves where the CSE is more pessimistic (or optimistic) than
  // the rep's best-case line. Glean context (when provided) explains
  // WHY and flags additive risk; not an action plan.
  const mlMismatchOpps = selectMlOverrideMismatchOpps(bucket.rows);
  const mlMismatchTotal = mlMismatchOpps.reduce(
    (s, r) => s + Math.abs(r.gapUSD),
    0,
  );
  lines.push(
    `Renewals where ML Override ≠ Best Case: ${fmtUSD(mlMismatchTotal)} total gap`,
  );
  lines.push(
    ...renderMlOverrideMismatchSection(
      mlMismatchOpps,
      mlOverrideMismatchContext,
    ),
  );
  lines.push('');

  // Churn-save targets MDAS believes belong in the hedge list but that
  // currently carry $0 forecast hedge — i.e., renewals at Confirmed
  // Churn / Saveable Risk (or with explicit churn dollars) that the CSE
  // hasn't yet pulled onto the Clari hedge line. This is the explicit
  // "we should call them out" ask: surface saves that aren't yet on
  // the manager's roll-up so leadership can decide to hedge them.
  const hedgedIds = new Set(sortedHedgeAccounts.map((r) => r.view.account.accountId));
  const targetsWithoutHedgeSeen = new Map<
    string,
    { view: AccountView; opp: CanonicalOpportunity; usd: number }
  >();
  for (const r of bucket.rows) {
    if (!isChurnSaveTarget(r.view, r.opp)) continue;
    if ((r.opp.forecastHedgeUSD ?? 0) > 0) continue;
    if (hedgedIds.has(r.view.account.accountId)) continue;
    const atr = r.opp.availableToRenewUSD ?? r.opp.acv ?? 0;
    if (atr <= 0) continue;
    const prev = targetsWithoutHedgeSeen.get(r.view.account.accountId);
    if (!prev || atr > prev.usd) {
      targetsWithoutHedgeSeen.set(r.view.account.accountId, {
        view: r.view,
        opp: r.opp,
        usd: atr,
      });
    }
  }
  const targetsWithoutHedge = Array.from(targetsWithoutHedgeSeen.values())
    .sort((a, b) => b.usd - a.usd)
    .slice(0, 5);
  const targetsWithoutHedgeTotal = targetsWithoutHedge.reduce(
    (s, r) => s + r.usd,
    0,
  );
  lines.push(
    `Churn-save targets not yet hedged in Clari (ATR exposed): ${fmtUSD(targetsWithoutHedgeTotal)}`,
  );
  if (targetsWithoutHedge.length === 0) {
    lines.push(`  - None identified`);
  } else {
    for (const r of targetsWithoutHedge) {
      lines.push(renderAccountBullet(r.view, r.opp, r.usd, ' ATR'));
    }
  }
  lines.push('');

  // Glean-flagged emerging risks — accounts the deterministic
  // structured filter did NOT catch but that show soft churn signals
  // in Slack / Gmail / account plans / CSE notes / meeting
  // transcripts. Bounded to this quarter by the upstream caller.
  // Rendered as a sibling sub-section under the structured
  // "not yet hedged" block so leadership reads "MDAS structurally
  // flagged these" + "Glean qualitatively flagged these" together.
  //
  // Dedup: we drop any Glean entry whose accountId already appears
  // anywhere in this quarter's structured per-account sections
  // (Accounts with Hedge, not-yet-hedged). Those accounts are
  // already on the manager's read; Glean's job here is to surface
  // accounts that AREN'T on it.
  //
  // The block is omitted entirely when (a) no Glean entries exist
  // for this quarter, or (b) every entry was deduped against
  // structured rows.
  const quarterFlag = isCurrent ? 'current' : 'next';
  const flaggedForQuarter = (gleanFlaggedRisks ?? []).filter(
    (r) => r.quarter === quarterFlag,
  );
  if (flaggedForQuarter.length > 0) {
    const structurallyFlaggedIds = new Set<string>([
      ...hedgedIds,
      ...targetsWithoutHedge.map((r) => r.view.account.accountId),
    ]);
    const dedupedFlagged = flaggedForQuarter.filter(
      (r) => !structurallyFlaggedIds.has(r.accountId),
    );
    if (dedupedFlagged.length > 0) {
      lines.push(
        `Glean-flagged emerging risks (soft signals, not yet in Clari):`,
      );
      for (const r of dedupedFlagged) {
        const rationale = r.rationale.trim();
        lines.push(
          rationale
            ? `  - ${r.accountName} - ${rationale}`
            : `  - ${r.accountName}`,
        );
      }
      lines.push('');
    }
  }

  // "Accounts to Close Gap" — same churn-save filter, then rank by ATR
  // (dollars that move the gap-to-Plan needle), not by total ACV. We
  // still bias toward red over yellow because that's where save effort
  // is highest leverage. Selection is shared with
  // `closeGapAccountContexts` so the Glean action plans key on exactly
  // these accounts.
  const gapAccounts = selectCloseGapAccounts(bucket.rows);
  const totalGapATR = gapAccounts.reduce((sum, r) => sum + r.usd, 0);
  lines.push(`Accounts to Close Gap (churn-save renewals): ${fmtUSD(totalGapATR)}`);
  if (gapAccounts.length === 0) {
    lines.push(`  - None identified`);
  } else {
    for (const r of gapAccounts) {
      lines.push(renderAccountBullet(r.view, r.opp, r.usd, ' ATR'));
      // Per 2026-05-29 user feedback: each Close-Gap account carries a
      // Glean-generated owner→action checklist, regenerated every run.
      // Rendered inline (indented) beneath the bullet so leadership
      // reads "who does what to close this" in the same place.
      lines.push(
        ...renderCloseGapActionPlan(closeGapActionPlans?.[r.view.account.accountId]),
      );
    }
  }
  lines.push('');

  // Week-over-week — placed above Key Saves so leadership sees what
  // moved this week before drilling into per-account narrative.
  // (Moved from below Key Saves on 2026-05-20.)
  const { summaries: wow, header: wowHeader } = wowChanges(bucket.rows, events);
  lines.push(
    `Week-over-week Changes - Improvements and increased risk: ${formatWowHeaderSummary(wowHeader)}`,
  );
  if (wow.length === 0) {
    lines.push(`  - No movement this week`);
  } else {
    for (const w of wow) {
      const detail = w.details
        .map((d) => `${d.sign === '-' ? '↓' : '↑'} ${d.text}`)
        .join('; ');
      lines.push(`  ${w.sign} ${w.accountName} - ${detail}`);
    }
  }
  lines.push('');

  lines.push(
    `Key Saves/Improvements to close the gap from Total Churn/Downsell risk to Flash:`,
  );

  // Red — risk trending; current quarter only per the template ("Accounts in red - risk trending" appears in current quarter section).
  // Per 2026-05-21 user feedback the Key Saves bullets are where the
  // qualitative Glean context goes (the other three sections above
  // keep just the structured chip line). We funnel red / yellow /
  // green through renderAccountBullet with the accountContext map so
  // the Glean blurb is spliced on exactly here.
  if (isCurrent) {
    const reds = topAccountsToCloseGap(bucket.rows, 'red', 5);
    lines.push(`Accounts in red - risk trending:`);
    if (reds.length === 0) lines.push(`  - None`);
    for (const r of reds) {
      lines.push(renderAccountBullet(r.view, r.opp, r.usd, '', accountContext));
    }
  }

  const yellows = topAccountsToCloseGap(bucket.rows, 'yellow', 5);
  lines.push(`Accounts in yellow - path to add hedge to the line:`);
  if (yellows.length === 0) lines.push(`  - None`);
  for (const r of yellows) {
    lines.push(renderAccountBullet(r.view, r.opp, r.usd, '', accountContext));
  }

  const greens = topAccountsToCloseGap(bucket.rows, 'green', 5);
  lines.push(`Accounts in green - path to capture the existing hedge already in the line:`);
  if (greens.length === 0) lines.push(`  - None`);
  for (const r of greens) {
    lines.push(renderAccountBullet(r.view, r.opp, r.usd, '', accountContext));
  }
  lines.push('');

  return lines;
}

/**
 * Generate the churn-call forecast script.
 *
 * Audience: CSE manager → leadership (plaintext, paste-ready).
 *
 * Design constraints (per 2026-04-29 user feedback):
 *   - Plaintext only. No markdown links, bold, or footnotes — the
 *     downstream surface is a Slack/email plaintext field.
 *   - Lens: CSE manager. Do not surface hygiene call-outs or coaching
 *     prompts; leadership doesn't act on those. Focus exclusively on
 *     revenue (churn risk, churn prevention, saves, hedges).
 *   - Two quarters: the quarter containing asOfDate, then the next.
 *   - Template structure follows the manager's existing script
 *     verbatim: Plan / Flash / Gap / Total Risk / Hedge / Accounts to
 *     Close Gap / Key Saves (red/yellow/green) / WoW changes.
 */
export function generateWeeklyForecast(input: ForecastInput): string {
  const { current, next } = bucketByQuarter(input.views, input.asOfDate);
  const lines: string[] = [];

  const clariRows = input.clariManagerForecastCsv
    ? parseClariManagerForecastExportCsv(input.clariManagerForecastCsv)
    : [];

  const stamp = new Date().toISOString().slice(0, 10);
  lines.push(`Expand 3 Quarterly Churn Forecast - ${stamp}`);
  lines.push('');

  lines.push(
    ...renderQuarterSection(
      current,
      input.changeEvents,
      input.plan?.currentQuarterUSD,
      true,
      clariRows,
      input.healthSnapshot?.currentQuarter,
      input.accountContext,
      input.gleanFlaggedRisks,
      input.closeGapActionPlans,
      input.mlOverrideMismatchContext,
    ),
  );
  lines.push(
    ...renderQuarterSection(
      next,
      input.changeEvents,
      input.plan?.nextQuarterUSD,
      false,
      clariRows,
      input.healthSnapshot?.nextQuarter,
      input.accountContext,
      input.gleanFlaggedRisks,
      input.closeGapActionPlans,
      input.mlOverrideMismatchContext,
    ),
  );

  return lines.join('\n').trimEnd() + '\n';
}

/** New name; same function — for callers that want the explicit intent. */
export const generateChurnCallScript = generateWeeklyForecast;
